### ISSUE TITLE
report issue

### ISSUE THREAD

**Issue by kiol1812** [Shinatsu94/NFU_2_1_DataStructure#1]
Please use PDF or Markdown instead of Word.

**Comment by Shinatsu94** [comment]
> Please use PDF or Markdown instead of Word.

In that time, My code is done not yet.
I was done HW2's all code and report is on 7 hour ago (04:00 am).
My report is upload now.

**Comment by kiol1812** [comment]
ok.
but, refer to [this](https://github.com/NFU-OpenDataStructure/NFU-DS-ProjectInstruction).
...
其中您的報告需要有以下部分：

解題說明（15%）
程式實作（30%）
效能分析（10%）
測試與驗證（20%）
**申論及開發報告**（25%）
...
You should write "申論及開發報告" instead of "心得".
When you are done, please reply this comment. (By 2024/12/01 at the latest)

**Comment by kiol1812** [comment]
At that time, we only saw this report
<https://github.com/Shinatsu94/NFU_2_1_DataStructure/commit/209cfb6b0850c99fa136b4a8511e9c42fb6efc37#diff-fbe80d64362a482db69af14f5d0064f596abb5b5464937571f20f40c365f1f73>
.

Shinatsu ***@***.***>於 2024年11月28日 週四，10:34寫道：

**Comment by Shinatsu94** [comment]
> ok. but, refer to [this](https://github.com/NFU-OpenDataStructure/NFU-DS-ProjectInstruction). ... 其中您的報告需要有以下部分：
> 
> 解題說明（15%） 程式實作（30%） 效能分析（10%） 測試與驗證（20%） **申論及開發報告**（25%） ... You should write "申論及開發報告" instead of "心得". When you are done, please reply this comment. (By 2024/12/01 at the latest)

But in 「110-1 HomeWork 2 (1105).ppt」this file, it say：
- 解題說明 **10%**
  - 想法(Ho to do?)陳述，並舉例說明。
- Algorithm Design & Programming **40%**
  - Source code + Comment
- 效能分析(Analysis) 15%
  - Time complexity & Space complexity
- 測試與認證(Testing and Proving) **15%**
- 效能量測(Measuring) 10%
- 心得討論 10%

So, i should readed mainly [scoring criteria](https://github.com/NFU-OpenDataStructure/NFU-DS-ProjectInstruction) on github, not readed [the file](https://ulearn.nfu.edu.tw/course/29250/learning-activity#/191799) on uleran?

btw, What is the「申論及開發報告」?
My 「解題說明」in report.pdf did not meet the question?
plz tell me what can I write for「申論及開發報告」.

![螢幕擷取畫面 2024-11-28 132216](https://github.com/user-attachments/assets/035d240f-b355-4516-9576-a00448c79b21)

**Comment by kiol1812** [comment]
So, i should readed mainly [scoring criteria](https://github.com/NFU-OpenDataStructure/NFU-DS-ProjectInstruction) on github, not readed [the file](https://ulearn.nfu.edu.tw/course/29250/learning-activity#/191799) on uleran?
└── yes. This information has been posted in Ulearn. ( 2024/11/25, sorry )
![image](https://github.com/user-attachments/assets/47752d69-5ea9-4f4e-bdc6-6a3dd1ebfc23)

For emample, in the caas of this HW.
"解題說明" should describe how you define the problem and your idea for solving it.
"申論及開發報告"  should describe the problem-solving process, potential improvements to your program, the characteristics of your program, etc.

**Comment by Shinatsu94** [comment]
> For emample, in the caas of this HW.
> ...

Ok, i got it.
But i think i cant immediately to fix my report file, When is upload deadline?

if i fix done my report file, i will reply this comment.

btw, can i save this original report file? or must to detele it on github?
(if can save it, i will rename its to "old_report.pdf")

**Comment by kiol1812** [comment]
> When you are done, please reply this comment. (By 2024/12/01 at the latest)  

You can create a folder to save it.
```plain
Homework_2/
├── src/
├── report.pdf
└── record/(here)
```

**Comment by Shinatsu94** [comment]
The new report is upload. by 11/30 17:56.
